name: CI github actions
on:
    push:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Descargando repositorio
              uses: actions/checkout@v4
            - name: Listando archivos
              run: ls -lha
            - name: Configurando credenciales AWS
              uses: aws-actions/configure-aws-credentials@v5.0.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

